version: 1
disable_existing_loggers: false

formatters:
  default:
    format: "%(asctime)s [%(levelname)s] [%(name)s] - %(message)s"
    datefmt: "%Y-%m-%d %H:%M:%S"

handlers:
  console:
    class: logging.StreamHandler
    formatter: default
    level: INFO
  file:
    class: logging.handlers.RotatingFileHandler
    filename: app.log
    maxBytes: 10485760   # 10 MB
    backupCount: 5
    formatter: default
    level: INFO

loggers:
  uvicorn:
    handlers: [ console, file ]
    level: INFO
    propagate: false
  uvicorn.error:
    handlers: [ console, file ]
    level: INFO
    propagate: false
  uvicorn.access:
    handlers: [ console, file ]
    level: INFO
    propagate: false
  app:
    handlers: [ console, file ]
    level: INFO
    propagate: false

root:
  handlers: [ console, file ]
  level: INFO
